Add setup.py file
sugarlabs/XaoS pull request #4
Opened 2019-01-19 10:44 UTC by nswarup14

Fixes #2 
Thanks

2019-01-19 11:44 UTC, pro-panda commented on setup.py
> +    bundlebuilder.start()
Missing newline

2019-01-19 11:45 UTC, rhl-bthr requested changes
Thanks, reviewed

2019-01-21 04:10 UTC, nswarup14 commented
@pro-panda 
Added the newline
Please review, thanks

2019-01-21 10:46 UTC, nswarup14 commented on setup.py
> +    bundlebuilder.start()
Done

2019-01-23 04:46 UTC, pro-panda commented
Thanks

2019-01-23 04:47 UTC, merged